basePath: /api/v1
definitions:
  main.UserInfo:
    properties:
      age:
        type: integer
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample Server pets
  title: ToDoList API
  version: 0.0.1
paths:
  /api/v1/userinfo/{id}:
    get:
      parameters:
      - description: 标签ID
        in: body
        name: user_id
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/main.UserInfo'
        "400":
          description: 请求错误
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 获取user详细
swagger: "2.0"
