version: "3.7"

networks:
  nats-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.255.0/24
      driver: default
services:
  nats-single:
    command:
      - "--debug"
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
    image: "nats:2.9.14"
    container_name: nats-single
    hostname: nats-single
    networks:
      nats-net:
        ipv4_address: 172.25.255.100
    ports:
      - "14222:4222"
      - "18222:8222"
    expose:
      - 4222
      - 8222