version: "3.7"

networks:
  nats-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.255.0/24
      driver: default
services:
  nats-1:
    command: "--debug --cluster_name NATS --cluster nats://0.0.0.0:6222 --port 4222 --http_port 8222"
    image: "nats:2.9.14"
    networks:
      nats-net:
        ipv4_address: 172.25.255.100
    ports:
      - "14222:4222"
      - "18222:8222"
    expose:
      - 4222
      - 6222
      - 8222
  nats-2:
    command: "--debug --cluster_name NATS --cluster nats://0.0.0.0:6222 --port 4222 --http_port 8222 --routes=nats://nats-1:6222 "
    image: "nats:2.9.14"
    networks:
      nats-net:
        ipv4_address: 172.25.255.101
    ports:
      - "24222:4222"
      - "28222:8222"
    expose:
      - 4222
      - 6222
      - 8222
    depends_on:
      - nats-1
  nats-3:
    command: "--debug --cluster_name NATS --cluster nats://0.0.0.0:6222 --port 4222 --http_port 8222 --routes=nats://nats-1:6222 "
    image: "nats:2.9.14"
    networks:
      nats-net:
        ipv4_address: 172.25.255.102
    ports:
      - "34222:4222"
      - "38222:8222"
    expose:
      - 4222
      - 6222
      - 8222
    depends_on:
      - nats-1